### ISSUE TITLE
Undefined method 'actors' for Flipper::UI::Configuration

### ISSUE THREAD

**Issue by IanVaughan** [jnunemaker/flipper#471]
After upgrading from 0.17.2 to:

```
  * flipper (0.18.0)
  * flipper-active_record (0.18.0)
  * flipper-ui (0.18.0)
```

I get an error in tests and booting the app:
```
       NoMethodError: undefined method `actors' for #<Flipper::UI::Configuration:0x0000562484f32dd0>
       /app/config/initializers/flipper.rb:7:in `block in <main>'
       /app/vendor/bundle/ruby/2.7.0/gems/flipper-ui-0.18.0/lib/flipper/ui.rb:58:in `configure'
       /app/config/initializers/flipper.rb:4:in `<main>'
```

**Comment by jnunemaker** [comment]
I mentioned it in the changleog. These went away because they have new and improved text. I’m not opposed to finding a way to add them back in if they are really necessary. For now, remove them and see what the new text is like and what you think. I could definitely see adding the description back in for config, I’m just not sure about title.
